"""empty message

Revision ID: 240e4820b57f
Revises: 2818b3306f98
Create Date: 2019-03-01 15:05:50.469886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '240e4820b57f'
down_revision = '2818b3306f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uptimes', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('uptimes', sa.Column('start_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uptimes', 'start_time')
    op.drop_column('uptimes', 'end_time')
    # ### end Alembic commands ###
