"""empty message

Revision ID: 4866fd4cac86
Revises: 2592601bf84f
Create Date: 2019-02-06 10:20:04.159982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4866fd4cac86'
down_revision = '2592601bf84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date_modified', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date_modified')
    # ### end Alembic commands ###
