"""empty message

Revision ID: 4b0e81ab57d0
Revises: b8a9a7eb442a
Create Date: 2019-02-28 11:24:40.338032

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4b0e81ab57d0'
down_revision = 'b8a9a7eb442a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_limits', sa.Column('access_type', mysql.TINYINT(display_width=1, unsigned=True), nullable=True))
    op.add_column('data_limits', sa.Column('gw_id', sa.String(), nullable=True))
    op.add_column('data_limits', sa.Column('limit_type', mysql.TINYTEXT(), nullable=True))
    op.create_foreign_key(None, 'data_limits', 'gateways', ['gw_id'], ['gw_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_limits', type_='foreignkey')
    op.drop_column('data_limits', 'limit_type')
    op.drop_column('data_limits', 'gw_id')
    op.drop_column('data_limits', 'access_type')
    # ### end Alembic commands ###
