"""empty message

Revision ID: 74563614a54e
Revises: 4b0e81ab57d0
Create Date: 2019-02-28 11:29:33.955872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74563614a54e'
down_revision = '4b0e81ab57d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_limits', sa.Column('access_type', sa.SmallInteger(), nullable=True))
    op.add_column('data_limits', sa.Column('gw_id', sa.String(), nullable=True))
    op.add_column('data_limits', sa.Column('limit_type', sa.String(length=2), nullable=True))
    op.create_foreign_key(None, 'data_limits', 'gateways', ['gw_id'], ['gw_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_limits', type_='foreignkey')
    op.drop_column('data_limits', 'limit_type')
    op.drop_column('data_limits', 'gw_id')
    op.drop_column('data_limits', 'access_type')
    # ### end Alembic commands ###
