"""empty message

Revision ID: 86bc7594ec32
Revises: 240e4820b57f
Create Date: 2019-03-04 10:59:48.660540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bc7594ec32'
down_revision = '240e4820b57f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcements')
    # ### end Alembic commands ###
