"""empty message

Revision ID: 9d782f19f076
Revises: 7975d4d40d0a
Create Date: 2019-03-01 14:47:21.802772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d782f19f076'
down_revision = '7975d4d40d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uptimes', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('uptimes', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uptimes', 'start_time')
    op.drop_column('uptimes', 'end_time')
    # ### end Alembic commands ###
