"""empty message

Revision ID: b346e5ec97b0
Revises: eebfee8fafcf
Create Date: 2019-02-07 10:48:11.344518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b346e5ec97b0'
down_revision = 'eebfee8fafcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(), nullable=True),
    sa.Column('registered_data', sa.Float(), nullable=True),
    sa.Column('month_data', sa.Float(), nullable=True),
    sa.Column('registered_limit', sa.Float(), nullable=True),
    sa.Column('month_limit', sa.Float(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('last_active', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_active')
    op.drop_table('registered_users')
    # ### end Alembic commands ###
