"""empty message

Revision ID: b8a9a7eb442a
Revises: cd83e28efadf
Create Date: 2019-02-28 11:23:47.822503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8a9a7eb442a'
down_revision = 'cd83e28efadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_limits_gw_id_fkey', 'data_limits', type_='foreignkey')
    op.drop_column('data_limits', 'access_type')
    op.drop_column('data_limits', 'limit_type')
    op.drop_column('data_limits', 'gw_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_limits', sa.Column('gw_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('data_limits', sa.Column('limit_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('data_limits', sa.Column('access_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('data_limits_gw_id_fkey', 'data_limits', 'gateways', ['gw_id'], ['id'])
    # ### end Alembic commands ###
