"""empty message

Revision ID: b8d561d75b4a
Revises: b346e5ec97b0
Create Date: 2019-02-08 14:24:35.419904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d561d75b4a'
down_revision = 'b346e5ec97b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('last_record', sa.Float(), nullable=True))
    op.add_column('registered_users', sa.Column('last_record', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registered_users', 'last_record')
    op.drop_column('devices', 'last_record')
    # ### end Alembic commands ###
