"""empty message

Revision ID: cd83e28efadf
Revises: e2307bed73ed
Create Date: 2019-02-28 11:14:25.117981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd83e28efadf'
down_revision = 'e2307bed73ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('data_limits_gw_id_fkey', 'data_limits', type_='foreignkey')
    op.create_foreign_key(None, 'data_limits', 'gateways', ['gw_id'], ['gw_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_limits', type_='foreignkey')
    op.create_foreign_key('data_limits_gw_id_fkey', 'data_limits', 'gateways', ['gw_id'], ['id'])
    # ### end Alembic commands ###
