"""empty message

Revision ID: e07e277fdd41
Revises: 1196325fae65
Create Date: 2019-02-04 04:10:33.653822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07e277fdd41'
down_revision = '1196325fae65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('stage', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'stage')
    # ### end Alembic commands ###
