"""empty message

Revision ID: e6ca5ff1caa5
Revises: d5b62cff70ee
Create Date: 2019-02-27 17:10:56.537993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ca5ff1caa5'
down_revision = 'd5b62cff70ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.String(), nullable=True),
    sa.Column('limit_type', sa.String(), nullable=True),
    sa.Column('gw_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_limits')
    # ### end Alembic commands ###
