"""empty message

Revision ID: 0056469a676d
Revises: 10e82792c1c6
Create Date: 2019-03-27 15:10:00.673771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0056469a676d'
down_revision = '10e82792c1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('announcements_gw_id_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    op.alter_column('data_limits', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('data_limits_gw_id_fkey', 'data_limits', type_='foreignkey')
    op.create_foreign_key(None, 'data_limits', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    op.alter_column('logos', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('logos_gw_id_fkey', 'logos', type_='foreignkey')
    op.create_foreign_key(None, 'logos', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    op.alter_column('uptimes', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('uptimes_gw_id_fkey', 'uptimes', type_='foreignkey')
    op.create_foreign_key(None, 'uptimes', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uptimes', type_='foreignkey')
    op.create_foreign_key('uptimes_gw_id_fkey', 'uptimes', 'gateways', ['gw_id'], ['gw_id'], ondelete='CASCADE')
    op.alter_column('uptimes', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'logos', type_='foreignkey')
    op.create_foreign_key('logos_gw_id_fkey', 'logos', 'gateways', ['gw_id'], ['gw_id'], ondelete='CASCADE')
    op.alter_column('logos', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'data_limits', type_='foreignkey')
    op.create_foreign_key('data_limits_gw_id_fkey', 'data_limits', 'gateways', ['gw_id'], ['gw_id'], ondelete='CASCADE')
    op.alter_column('data_limits', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key('announcements_gw_id_fkey', 'announcements', 'gateways', ['gw_id'], ['gw_id'], ondelete='CASCADE')
    op.alter_column('announcements', 'gw_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
