"""empty message

Revision ID: 069ed76f154d
Revises: 3c20e4ac53b1
Create Date: 2019-04-05 17:58:00.880261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '069ed76f154d'
down_revision = '3c20e4ac53b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'data_limits', ['gw_id', 'access_type', 'limit_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_limits', type_='unique')
    # ### end Alembic commands ###
