"""empty message

Revision ID: 0a4c05f62fca
Revises: 8099635369e8
Create Date: 2019-04-17 17:42:57.949824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4c05f62fca'
down_revision = '8099635369e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'mpop_id')
    op.drop_column('admin_users', 'mpop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('mpop', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admin_users', sa.Column('mpop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
