"""empty message

Revision ID: 0ac09f58d44d
Revises: 10f6e50ff1b2
Create Date: 2019-03-21 11:07:51.801278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac09f58d44d'
down_revision = '10f6e50ff1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certified',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('cert_data', sa.Float(), nullable=True),
    sa.Column('month_data', sa.Float(), nullable=True),
    sa.Column('last_record', sa.Float(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('radcheck', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('radcheck', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radcheck', 'token')
    op.drop_column('radcheck', 'status')
    op.drop_table('certified')
    # ### end Alembic commands ###
