"""empty message

Revision ID: 0cfbc323c1a2
Revises: 0a4c05f62fca
Create Date: 2019-04-17 17:43:30.099409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfbc323c1a2'
down_revision = '0a4c05f62fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('mpop_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'gateways', ['mpop_id'], ['gw_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'mpop_id')
    # ### end Alembic commands ###
