"""empty message

Revision ID: 10f6e50ff1b2
Revises: 3f7d1200adfe
Create Date: 2019-03-11 14:26:15.022658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10f6e50ff1b2'
down_revision = '3f7d1200adfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radcheck',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('attribute', sa.String(), nullable=True),
    sa.Column('op', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('id_type', sa.String(length=2), nullable=True),
    sa.Column('id_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radcheck')
    # ### end Alembic commands ###
