"""empty message

Revision ID: 2592601bf84f
Revises: 7932e619880f
Create Date: 2019-02-06 09:45:00.688278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2592601bf84f'
down_revision = '7932e619880f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('device', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'device')
    # ### end Alembic commands ###
