"""empty message

Revision ID: 261caff3b892
Revises: ac596b9c8750
Create Date: 2020-07-29 15:49:34.157403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261caff3b892'
down_revision = 'ac596b9c8750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_auth_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('acctstatustype', sa.String(), nullable=True),
    sa.Column('acctsessionid', sa.BigInteger(), nullable=True),
    sa.Column('nasidentifier', sa.String(), nullable=True),
    sa.Column('auth_mode', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('acctinputoctets', sa.BigInteger(), nullable=True),
    sa.Column('acctoutputoctets', sa.BigInteger(), nullable=True),
    sa.Column('framedipaddress', sa.String(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('username', 'time_stamp')
    )
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('mpop_id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mpop_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gw_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gw_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=False),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gw_id')
    )
    op.create_table('certified',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('common_name', sa.String(), nullable=True),
    sa.Column('cert_data', sa.Float(), nullable=True),
    sa.Column('month_data', sa.Float(), nullable=True),
    sa.Column('last_record', sa.Float(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_type', sa.SmallInteger(), nullable=True),
    sa.Column('limit_type', sa.String(length=2), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gw_id', 'access_type', 'limit_type')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('free_data', sa.Float(), nullable=True),
    sa.Column('month_data', sa.Float(), nullable=True),
    sa.Column('last_record', sa.Float(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gateway_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gateway_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gw_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['gateway_group.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['gateway_group.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=False),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gw_id')
    )
    op.create_table('redirect_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gw_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gw_id')
    )
    op.create_table('registered_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(), nullable=True),
    sa.Column('registered_data', sa.Float(), nullable=True),
    sa.Column('month_data', sa.Float(), nullable=True),
    sa.Column('last_record', sa.Float(), nullable=True),
    sa.Column('last_active', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_table('session_ids',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('session_id'),
    sa.UniqueConstraint('mac')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('mname', sa.String(), nullable=True),
    sa.Column('ename', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('id_type', sa.String(length=2), nullable=True),
    sa.Column('id_value', sa.String(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('registration_date', sa.String(), nullable=True),
    sa.Column('validated', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(), nullable=True),
    sa.Column('gw_sn', sa.String(), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('gw_address', sa.String(), nullable=True),
    sa.Column('gw_port', sa.String(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('apmac', sa.String(), nullable=True),
    sa.Column('ssid', sa.String(), nullable=True),
    sa.Column('vlanid', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('package', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('date_modified', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uptimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gw_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gw_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uptimes')
    op.drop_table('transactions')
    op.drop_table('subscribers')
    op.drop_table('session_ids')
    op.drop_table('roles')
    op.drop_table('registered_users')
    op.drop_table('redirect_links')
    op.drop_table('logos')
    op.drop_table('group_announcements')
    op.drop_table('gateways')
    op.drop_table('gateway_groups')
    op.drop_table('gateway_group')
    op.drop_table('devices')
    op.drop_table('data_limits')
    op.drop_table('certified')
    op.drop_table('announcements')
    op.drop_table('admin_users')
    op.drop_table('accounting')
    op.drop_table('access_auth_logs')
    # ### end Alembic commands ###
