"""empty message

Revision ID: 2b6e31bdb5a4
Revises: 0ac09f58d44d
Create Date: 2019-03-26 18:07:29.101405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6e31bdb5a4'
down_revision = '0ac09f58d44d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('announcements_gw_id_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    op.drop_constraint('data_limits_gw_id_fkey', 'data_limits', type_='foreignkey')
    op.create_foreign_key(None, 'data_limits', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    op.drop_constraint('logos_gw_id_fkey', 'logos', type_='foreignkey')
    op.create_foreign_key(None, 'logos', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    op.drop_constraint('uptimes_gw_id_fkey', 'uptimes', type_='foreignkey')
    op.create_foreign_key(None, 'uptimes', 'gateways', ['gw_id'], ['gw_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uptimes', type_='foreignkey')
    op.create_foreign_key('uptimes_gw_id_fkey', 'uptimes', 'gateways', ['gw_id'], ['gw_id'])
    op.drop_constraint(None, 'logos', type_='foreignkey')
    op.create_foreign_key('logos_gw_id_fkey', 'logos', 'gateways', ['gw_id'], ['gw_id'])
    op.drop_constraint(None, 'data_limits', type_='foreignkey')
    op.create_foreign_key('data_limits_gw_id_fkey', 'data_limits', 'gateways', ['gw_id'], ['gw_id'])
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key('announcements_gw_id_fkey', 'announcements', 'gateways', ['gw_id'], ['gw_id'])
    # ### end Alembic commands ###
