"""empty message

Revision ID: 38ebb9c9b24f
Revises: f6b0aeabc5f5
Create Date: 2019-04-16 10:01:57.585565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ebb9c9b24f'
down_revision = 'f6b0aeabc5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_limits', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('data_limits', sa.Column('created_on', sa.String(), nullable=True))
    op.create_foreign_key(None, 'data_limits', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    op.add_column('gateways', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('gateways', sa.Column('created_on', sa.String(), nullable=True))
    op.create_foreign_key(None, 'gateways', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gateways', type_='foreignkey')
    op.drop_column('gateways', 'created_on')
    op.drop_column('gateways', 'created_by_id')
    op.drop_constraint(None, 'data_limits', type_='foreignkey')
    op.drop_column('data_limits', 'created_on')
    op.drop_column('data_limits', 'created_by_id')
    # ### end Alembic commands ###
