"""empty message

Revision ID: 3c20e4ac53b1
Revises: d5a7a8a739a4
Create Date: 2019-04-05 16:27:29.551679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c20e4ac53b1'
down_revision = 'd5a7a8a739a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('announcements_modified_by_id_key', 'announcements', type_='unique')
    op.drop_constraint('data_limits_modified_by_id_key', 'data_limits', type_='unique')
    op.drop_constraint('gateways_modified_by_id_key', 'gateways', type_='unique')
    op.drop_constraint('logos_modified_by_id_key', 'logos', type_='unique')
    op.drop_constraint('uptimes_modified_by_id_key', 'uptimes', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uptimes_modified_by_id_key', 'uptimes', ['modified_by_id'])
    op.create_unique_constraint('logos_modified_by_id_key', 'logos', ['modified_by_id'])
    op.create_unique_constraint('gateways_modified_by_id_key', 'gateways', ['modified_by_id'])
    op.create_unique_constraint('data_limits_modified_by_id_key', 'data_limits', ['modified_by_id'])
    op.create_unique_constraint('announcements_modified_by_id_key', 'announcements', ['modified_by_id'])
    # ### end Alembic commands ###
