"""empty message

Revision ID: 3f7d1200adfe
Revises: e84f077f8788
Create Date: 2019-03-06 15:22:52.125066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7d1200adfe'
down_revision = 'e84f077f8788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin_users', ['username'])
    op.drop_constraint('data_limits_gw_id_access_type_limit_type_key', 'data_limits', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('data_limits_gw_id_access_type_limit_type_key', 'data_limits', ['gw_id', 'access_type', 'limit_type'])
    op.drop_constraint(None, 'admin_users', type_='unique')
    # ### end Alembic commands ###
