"""empty message

Revision ID: 428129913c72
Revises: c61d5773ec15
Create Date: 2019-04-22 11:02:54.176181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '428129913c72'
down_revision = 'c61d5773ec15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('created_on', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_users', 'created_on')
    # ### end Alembic commands ###
