"""empty message

Revision ID: 530a66d29ed5
Revises: 87a4e2880670
Create Date: 2019-05-02 17:02:00.946987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '530a66d29ed5'
down_revision = '87a4e2880670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gateway_groups_modified_by_id_fkey', 'gateway_groups', type_='foreignkey')
    op.drop_constraint('gateway_groups_created_by_id_fkey', 'gateway_groups', type_='foreignkey')
    op.drop_column('gateway_groups', 'modified_by_id')
    op.drop_column('gateway_groups', 'modified_on')
    op.drop_column('gateway_groups', 'created_by_id')
    op.drop_column('gateway_groups', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_groups', sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gateway_groups', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gateway_groups', sa.Column('modified_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('gateway_groups', sa.Column('modified_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('gateway_groups_created_by_id_fkey', 'gateway_groups', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('gateway_groups_modified_by_id_fkey', 'gateway_groups', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
