"""empty message

Revision ID: 5a3c3fc67d11
Revises: 428129913c72
Create Date: 2019-04-22 14:11:00.056673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3c3fc67d11'
down_revision = '428129913c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gateway_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gw_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['gateway_group.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gateway_groups')
    op.drop_table('gateway_group')
    # ### end Alembic commands ###
