"""empty message

Revision ID: 5b9dda8a4718
Revises: 86bc7594ec32
Create Date: 2019-03-05 11:45:14.156816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b9dda8a4718'
down_revision = '86bc7594ec32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('announcements', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('data_limits', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('gateways', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.add_column('uptimes', sa.Column('status', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uptimes', 'status')
    op.drop_column('gateways', 'status')
    op.drop_column('data_limits', 'status')
    op.drop_column('announcements', 'status')
    op.drop_table('logos')
    # ### end Alembic commands ###
