"""empty message

Revision ID: 5f62ba413cc3
Revises: 815df6a08f58
Create Date: 2019-05-08 11:26:57.658614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f62ba413cc3'
down_revision = '815df6a08f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_auth_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('gw_id', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('time_stamp', sa.BigInteger(), nullable=False),
    sa.Column('acctstatustype', sa.String(), nullable=True),
    sa.Column('acctsessionid', sa.String(), nullable=True),
    sa.Column('nasidentifier', sa.String(), nullable=True),
    sa.Column('auth_mode', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('acctinputoctets', sa.BigInteger(), nullable=True),
    sa.Column('acctoutputoctets', sa.BigInteger(), nullable=True),
    sa.Column('framedipaddress', sa.String(), nullable=True),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('username', 'time_stamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting')
    op.drop_table('access_auth_logs')
    # ### end Alembic commands ###
