"""empty message

Revision ID: 63b4149d6da0
Revises: 77725870ec8b
Create Date: 2019-04-15 15:46:51.058518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b4149d6da0'
down_revision = '77725870ec8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_users_mpop_id_fkey', 'admin_users', type_='foreignkey')
    op.create_foreign_key(None, 'admin_users', 'gateways', ['mpop_id'], ['gw_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.create_foreign_key('admin_users_mpop_id_fkey', 'admin_users', 'gateways', ['mpop_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
