"""empty message

Revision ID: 6ad19c41ff08
Revises: 85b8b0e59596
Create Date: 2019-04-15 14:40:19.616373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad19c41ff08'
down_revision = '85b8b0e59596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'role')
    )
    op.add_column('admin_users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'admin_users', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('admin_users', 'role')
    op.add_column('radcheck', sa.Column('registration_date', sa.String(), nullable=True))
    op.add_column('radcheck', sa.Column('validated', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('radcheck', 'validated')
    op.drop_column('radcheck', 'registration_date')
    op.add_column('admin_users', sa.Column('role', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
