"""empty message

Revision ID: 760491997a55
Revises: aacd343a4982
Create Date: 2019-04-22 15:30:15.453236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '760491997a55'
down_revision = 'aacd343a4982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('path', sa.Unicode(length=128), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('modified_by_id', sa.Integer(), nullable=False),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['group_id'], ['gateway_group.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_announcements')
    # ### end Alembic commands ###
