"""empty message

Revision ID: 7975d4d40d0a
Revises: a9208ad2fa27
Create Date: 2019-03-01 14:46:55.236557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7975d4d40d0a'
down_revision = 'a9208ad2fa27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uptimes', 'end_time')
    op.drop_column('uptimes', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uptimes', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('uptimes', sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
