"""empty message

Revision ID: 7e3f49635a12
Revises: b8e5539fefea
Create Date: 2019-04-16 10:28:18.387217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e3f49635a12'
down_revision = 'b8e5539fefea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('created_on', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gateways', 'created_on')
    # ### end Alembic commands ###
