"""empty message

Revision ID: 8099635369e8
Revises: 14f3a070949a
Create Date: 2019-04-17 17:40:51.271548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8099635369e8'
down_revision = '14f3a070949a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'admin_users', 'gateways', ['mpop_id'], ['gw_id'], ondelete='RESTRICT')
    op.drop_column('admin_users', 'mpop')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('mpop', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    # ### end Alembic commands ###
