"""empty message

Revision ID: 815df6a08f58
Revises: cdf3bf25314c
Create Date: 2019-05-02 17:23:40.120122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815df6a08f58'
down_revision = 'cdf3bf25314c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.add_column('admin_users', sa.Column('modified_on', sa.String(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'modified_on')
    op.drop_column('admin_users', 'modified_by_id')
    # ### end Alembic commands ###
