"""empty message

Revision ID: 85b8b0e59596
Revises: 069ed76f154d
Create Date: 2019-04-11 11:37:58.641408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b8b0e59596'
down_revision = '069ed76f154d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('mpop_id', sa.Integer(), nullable=True))
    op.add_column('admin_users', sa.Column('role', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'gateways', ['mpop_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'role')
    op.drop_column('admin_users', 'mpop_id')
    # ### end Alembic commands ###
