"""empty message

Revision ID: 87a4e2880670
Revises: 760491997a55
Create Date: 2019-05-02 16:48:42.680259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87a4e2880670'
down_revision = '760491997a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('fname', sa.String(), nullable=True),
    sa.Column('lname', sa.String(), nullable=True),
    sa.Column('mname', sa.String(), nullable=True),
    sa.Column('ename', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_no', sa.String(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('id_type', sa.String(length=2), nullable=True),
    sa.Column('id_value', sa.String(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('registration_date', sa.String(), nullable=True),
    sa.Column('validated', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('radcheck')
    op.alter_column('admin_users', 'mpop_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('gateway_groups', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('gateway_groups', sa.Column('created_on', sa.String(), nullable=True))
    op.add_column('gateway_groups', sa.Column('modified_by_id', sa.Integer(), nullable=False))
    op.add_column('gateway_groups', sa.Column('modified_on', sa.String(), nullable=True))
    op.create_foreign_key(None, 'gateway_groups', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'gateway_groups', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gateway_groups', type_='foreignkey')
    op.drop_constraint(None, 'gateway_groups', type_='foreignkey')
    op.drop_column('gateway_groups', 'modified_on')
    op.drop_column('gateway_groups', 'modified_by_id')
    op.drop_column('gateway_groups', 'created_on')
    op.drop_column('gateway_groups', 'created_by_id')
    op.alter_column('admin_users', 'mpop_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('radcheck',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attribute', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('op', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_no', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('id_type', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('id_value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('registration_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('validated', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='radcheck_pkey')
    )
    op.drop_table('subscribers')
    # ### end Alembic commands ###
