"""empty message

Revision ID: 9562a55822cd
Revises: 74563614a54e
Create Date: 2019-02-28 14:10:47.371836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9562a55822cd'
down_revision = '74563614a54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'month_limit')
    op.drop_column('devices', 'free_limit')
    op.drop_column('registered_users', 'registered_limit')
    op.drop_column('registered_users', 'month_limit')
    op.add_column('transactions', sa.Column('gw_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'gw_id')
    op.add_column('registered_users', sa.Column('month_limit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('registered_users', sa.Column('registered_limit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('free_limit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('month_limit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
