"""empty message

Revision ID: a9208ad2fa27
Revises: 9562a55822cd
Create Date: 2019-03-01 13:55:34.789504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9208ad2fa27'
down_revision = '9562a55822cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uptimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gw_id', sa.String(), nullable=True),
    sa.Column('start_time', sa.String(), nullable=True),
    sa.Column('end_time', sa.String(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_on', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gw_id'], ['gateways.gw_id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uptimes')
    # ### end Alembic commands ###
