"""empty message

Revision ID: ac1a88a5e487
Revises: fe043f08fce7
Create Date: 2019-04-17 17:35:46.932302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac1a88a5e487'
down_revision = 'fe043f08fce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_users_mpop_id_fkey', 'admin_users', type_='foreignkey')
    op.create_foreign_key(None, 'admin_users', 'gateways', ['mpop_id'], ['gw_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.create_foreign_key('admin_users_mpop_id_fkey', 'admin_users', 'gateways', ['mpop_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
