"""empty message

Revision ID: b8e5539fefea
Revises: 38ebb9c9b24f
Create Date: 2019-04-16 10:27:52.163237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e5539fefea'
down_revision = '38ebb9c9b24f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gateways', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
