"""empty message

Revision ID: bc74eb446ecc
Revises: 7e3f49635a12
Create Date: 2019-04-16 10:30:52.230194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc74eb446ecc'
down_revision = '7e3f49635a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('date_created', sa.String(), nullable=True))
    op.drop_column('gateways', 'created_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('created_on', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gateways', 'date_created')
    # ### end Alembic commands ###
