"""empty message

Revision ID: bdc564626051
Revises: 5f62ba413cc3
Create Date: 2019-05-08 11:35:00.041809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdc564626051'
down_revision = '5f62ba413cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_auth_logs', sa.Column('mac', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('access_auth_logs', 'mac')
    # ### end Alembic commands ###
