"""empty message

Revision ID: c61d5773ec15
Revises: ee8037ff1e65
Create Date: 2019-04-22 10:25:51.615979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61d5773ec15'
down_revision = 'ee8037ff1e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'admin_users', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.drop_column('admin_users', 'created_by_id')
    # ### end Alembic commands ###
