"""empty message

Revision ID: cdf3bf25314c
Revises: 530a66d29ed5
Create Date: 2019-05-02 17:02:40.083870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf3bf25314c'
down_revision = '530a66d29ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateway_group', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('gateway_group', sa.Column('created_on', sa.String(), nullable=True))
    op.add_column('gateway_group', sa.Column('modified_by_id', sa.Integer(), nullable=False))
    op.add_column('gateway_group', sa.Column('modified_on', sa.String(), nullable=True))
    op.add_column('gateway_group', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.create_foreign_key(None, 'gateway_group', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'gateway_group', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gateway_group', type_='foreignkey')
    op.drop_constraint(None, 'gateway_group', type_='foreignkey')
    op.drop_column('gateway_group', 'status')
    op.drop_column('gateway_group', 'modified_on')
    op.drop_column('gateway_group', 'modified_by_id')
    op.drop_column('gateway_group', 'created_on')
    op.drop_column('gateway_group', 'created_by_id')
    # ### end Alembic commands ###
