"""empty message

Revision ID: d241072146f1
Revises: ac1a88a5e487
Create Date: 2019-04-17 17:38:50.612497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd241072146f1'
down_revision = 'ac1a88a5e487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('mpop', sa.String(), nullable=True))
    op.drop_constraint('admin_users_mpop_id_fkey', 'admin_users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('admin_users_mpop_id_fkey', 'admin_users', 'gateways', ['mpop_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('admin_users', 'mpop')
    # ### end Alembic commands ###
