"""empty message

Revision ID: d5a7a8a739a4
Revises: 0056469a676d
Create Date: 2019-04-05 15:59:09.954638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a7a8a739a4'
down_revision = '0056469a676d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('announcements', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'announcements', ['modified_by_id'])
    op.drop_constraint('announcements_modified_by_id_fkey', 'announcements', type_='foreignkey')
    op.create_foreign_key(None, 'announcements', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('data_limits', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'data_limits', ['modified_by_id'])
    op.drop_constraint('data_limits_modified_by_id_fkey', 'data_limits', type_='foreignkey')
    op.create_foreign_key(None, 'data_limits', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('gateways', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'gateways', ['modified_by_id'])
    op.drop_constraint('gateways_modified_by_id_fkey', 'gateways', type_='foreignkey')
    op.create_foreign_key(None, 'gateways', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('logos', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'logos', ['modified_by_id'])
    op.drop_constraint('logos_modified_by_id_fkey', 'logos', type_='foreignkey')
    op.create_foreign_key(None, 'logos', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('uptimes', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'uptimes', ['modified_by_id'])
    op.drop_constraint('uptimes_modified_by_id_fkey', 'uptimes', type_='foreignkey')
    op.create_foreign_key(None, 'uptimes', 'admin_users', ['modified_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uptimes', type_='foreignkey')
    op.create_foreign_key('uptimes_modified_by_id_fkey', 'uptimes', 'admin_users', ['modified_by_id'], ['id'])
    op.drop_constraint(None, 'uptimes', type_='unique')
    op.alter_column('uptimes', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'logos', type_='foreignkey')
    op.create_foreign_key('logos_modified_by_id_fkey', 'logos', 'admin_users', ['modified_by_id'], ['id'])
    op.drop_constraint(None, 'logos', type_='unique')
    op.alter_column('logos', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'gateways', type_='foreignkey')
    op.create_foreign_key('gateways_modified_by_id_fkey', 'gateways', 'admin_users', ['modified_by_id'], ['id'])
    op.drop_constraint(None, 'gateways', type_='unique')
    op.alter_column('gateways', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'data_limits', type_='foreignkey')
    op.create_foreign_key('data_limits_modified_by_id_fkey', 'data_limits', 'admin_users', ['modified_by_id'], ['id'])
    op.drop_constraint(None, 'data_limits', type_='unique')
    op.alter_column('data_limits', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.create_foreign_key('announcements_modified_by_id_fkey', 'announcements', 'admin_users', ['modified_by_id'], ['id'])
    op.drop_constraint(None, 'announcements', type_='unique')
    op.alter_column('announcements', 'modified_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
