"""empty message

Revision ID: d5b62cff70ee
Revises: 959fa5c98050
Create Date: 2019-02-27 11:04:35.347192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b62cff70ee'
down_revision = '959fa5c98050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('modified_by_id', sa.Integer(), nullable=True))
    op.drop_constraint('gateways_modified_by_fkey', 'gateways', type_='foreignkey')
    op.create_foreign_key(None, 'gateways', 'admin_users', ['modified_by_id'], ['id'])
    op.drop_column('gateways', 'modified_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('modified_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gateways', type_='foreignkey')
    op.create_foreign_key('gateways_modified_by_fkey', 'gateways', 'admin_users', ['modified_by'], ['id'])
    op.drop_column('gateways', 'modified_by_id')
    # ### end Alembic commands ###
