"""empty message

Revision ID: daba79d21eec
Revises: 5b9dda8a4718
Create Date: 2019-03-05 11:51:33.270229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daba79d21eec'
down_revision = '5b9dda8a4718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'data_limits', ['gw_id', 'access_type', 'limit_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_limits', type_='unique')
    # ### end Alembic commands ###
