"""empty message

Revision ID: e10028cd7082
Revises: bc74eb446ecc
Create Date: 2019-04-16 10:48:16.529825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10028cd7082'
down_revision = 'bc74eb446ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('created_on', sa.String(), nullable=True))
    op.drop_column('gateways', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gateways', sa.Column('date_created', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('gateways', 'created_on')
    # ### end Alembic commands ###
