"""empty message

Revision ID: e2307bed73ed
Revises: e6ca5ff1caa5
Create Date: 2019-02-27 17:26:50.084412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2307bed73ed'
down_revision = 'e6ca5ff1caa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_limits', sa.Column('value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_limits', 'value')
    # ### end Alembic commands ###
