"""empty message

Revision ID: e84f077f8788
Revises: daba79d21eec
Create Date: 2019-03-05 11:55:42.483424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84f077f8788'
down_revision = 'daba79d21eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'announcements', ['gw_id'])
    op.create_unique_constraint(None, 'logos', ['gw_id'])
    op.create_unique_constraint(None, 'uptimes', ['gw_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uptimes', type_='unique')
    op.drop_constraint(None, 'logos', type_='unique')
    op.drop_constraint(None, 'announcements', type_='unique')
    # ### end Alembic commands ###
