"""empty message

Revision ID: eebfee8fafcf
Revises: 4866fd4cac86
Create Date: 2019-02-07 10:46:17.137984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebfee8fafcf'
down_revision = '4866fd4cac86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('free_data', sa.Float(), nullable=True),
    sa.Column('month_data', sa.Float(), nullable=True),
    sa.Column('free_limit', sa.Float(), nullable=True),
    sa.Column('month_limit', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
