"""empty message

Revision ID: f6b0aeabc5f5
Revises: 58220c6fc232
Create Date: 2019-04-15 15:50:27.999716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b0aeabc5f5'
down_revision = '58220c6fc232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_users_mpop_id_fkey', 'admin_users', type_='foreignkey')
    op.create_foreign_key(None, 'admin_users', 'gateways', ['mpop_id'], ['gw_id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_users', type_='foreignkey')
    op.create_foreign_key('admin_users_mpop_id_fkey', 'admin_users', 'gateways', ['mpop_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
