"""empty message

Revision ID: fe043f08fce7
Revises: e10028cd7082
Create Date: 2019-04-17 16:12:55.196367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe043f08fce7'
down_revision = 'e10028cd7082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('announcements', sa.Column('created_on', sa.String(), nullable=True))
    op.create_foreign_key(None, 'announcements', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    op.add_column('logos', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('logos', sa.Column('created_on', sa.String(), nullable=True))
    op.create_foreign_key(None, 'logos', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    op.add_column('uptimes', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.add_column('uptimes', sa.Column('created_on', sa.String(), nullable=True))
    op.create_foreign_key(None, 'uptimes', 'admin_users', ['created_by_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uptimes', type_='foreignkey')
    op.drop_column('uptimes', 'created_on')
    op.drop_column('uptimes', 'created_by_id')
    op.drop_constraint(None, 'logos', type_='foreignkey')
    op.drop_column('logos', 'created_on')
    op.drop_column('logos', 'created_by_id')
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_column('announcements', 'created_on')
    op.drop_column('announcements', 'created_by_id')
    # ### end Alembic commands ###
